name: Algoritmos
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    name: Inicio
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
          java-package: jdk
          architecture: x64
      - run: java -cp java Main