name: Algoritmos

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Algoritmos
    steps:
      - uses: actions/checkout@v2
      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: '11'
          java-package: jdk
          architecture: x64
      - run: ls
      - run: find . -type f -name "*.java" -print | xargs javac -d diretorios
      - run: ls diretorios