name: Algoritmos
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    name: coletaDados
    steps:
      - uses: actions/checkout@v2
      - name: Start JDK
        uses: actions/setup-java@v1
        with:
          java-version: '11'
          java-package: jdk
          architecture: x64
        working-directory: ./coletaDados/src
      - run: find . -type f -name "*.java" -print | xargs javac -d classes
      - run: java -cp "classes" src.Main