# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  #  pull_request:
  #    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    name: App
    steps:
      - uses: actions/checkout@v2
      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: '11' # The JDK version to make available on the path.
          java-package: jdk # (jre, jdk, or jdk+fx) - defaults to jdk
          architecture: x64 # (x64 or x86) - defaults to x64
      - run: find . -type f -name "*.java" -print | xargs javac -d classes # Compilar todos os ".java" para ".class" colocando pasta "classes"
      #      - run: javac -d classes ./src/helpers/ArquivoTextoLeitura.java
      #      - run: javac -d classes ./src/models/AtivoRegistro.java
      #      - run: javac -d classes -cp "classes" ./src/App.java
      - run: java -cp "classes" src.Test # Rodar o App.class do projeto que esta na pasta "classes"