name: Algoritmos
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    name: coletaDados
    steps:
      - uses: actions/checkout@v2
      - name: Start JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          java-package: jdk
          architecture: x64
      - run: ls