name: Algoritmos
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    name: Inicio
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '11'
      - run: cd coletaDados
        ls
